### ISSUE TITLE
Design proposal for diagnostics support in ros 2 

### ISSUE THREAD

**Issue by sagniknitr** [ros2/design#185]
Is there any proposal for how to support diagnostics inside ROS 2.0 ?

**Comment by tfoote** [comment]
I don't believe that anyone has looked at it much. By default we would keep using the ROS 1 approach http://www.ros.org/reps/rep-0107.html I don't think that there's anything incompatilbe in that defnition for a ROS 2 implementation. Any changes should be justified and evaluated for requirements for porting/migrating.

**Comment by sagniknitr** [comment]
Thanks @tfoote for the clarification.
