### ISSUE TITLE
feature request: Introspection into "nodelet-like" intra-process communication.

### ISSUE THREAD

**Issue by jbohren** [ros2/design#20]
Nodelets are mentioned in the DDL design page, and it was mentioned that a similar shared-pointer-like interface would be provided. I just wanted to mention the desire to have introspection into such intra-process communication. Currently with nodelets, there's no way to discern which topics are connected between which nodelet in a single nodelet manager, and as such, debugging can be frustrating and slow.

The previous discussion here ended with "let's get back to this when we're talking about ROS2" so I figured it was time to bring this back up: https://code.ros.org/trac/ros/ticket/3360 [(cached)](http://webcache.googleusercontent.com/search?q=cache:YHzE2TqlKhUJ:https://code.ros.org/trac/ros/ticket/3360+&cd=1&hl=en&ct=clnk&gl=us)

**Comment by wjwwood** [comment]
Yeah, I'm not sure if we need a new article or if it belongs in an existing one, but my current vision for the equivalent to nodelets is that internal connections are treated no different from external ones. Either way when we talk about process management this point needs to be addressed.

**Comment by dirk-thomas** [comment]
The composition has been implemented in a way that each component is still a node (see ros2/demos#84). So they are introspectable individually in the same way as they are when running in separate processes.
