### ISSUE TITLE
namespaces

### ISSUE THREAD

**Issue by BobDean** [ros2/design#25]
were nested or deep namespaces for messages considered? For example myproject::navigation::pose, or myproject::mobility::WaypointCmd ?

**Comment by wjwwood** [comment]
I hadn't considered this as a possibility, but it would be possible to have namespaces in messages. However, I'm not sure if that is necessary since you can use the containing package name as the namespace, i.e. `myproject::navigation::pose` => `myproject_navigation_msgs::pose`.
