### ISSUE TITLE
Write ament design document

### ISSUE THREAD

**Issue by wjwwood** [ros2/design#26]
AC:
- [x] Whitepaper describing build tool design
  - [x] appendix describing changes from catkin

**Comment by jackieokay** [comment]
Dirk started an effort in https://github.com/ros2/design/pull/38. Would you consider this issue closed or are you planning on expanding it?

http://design.ros2.org/articles/ament.html

**Comment by dirk-thomas** [comment]
The article does not yet cover the design but focuses on the differences to catkin.

**Comment by dirk-thomas** [comment]
With the recent merge of #44 I think ament is described well enough for now. If nobody disagrees I would close this ticket soon.

**Comment by wjwwood** [comment]
The only thing that I think we could describe in more detail is how we changed setup files in ament to have local and "recursive" setup files and that we use the tool to create top level setup files to avoid installation collisions where ever possible.

**Comment by wjwwood** [comment]
+1 to close with https://github.com/ros2/design/issues/45
