### ISSUE TITLE
Update Launch XML Schema

### ISSUE THREAD

**Issue by rob-clarke** [ros2/design#317]
Similar to #285 I believe the schema doesn't match the current implementation.

In the schema, the `<node>` element currently defines a `ns` attribute but this appears to have been renamed to `namespace`. At least if [here](https://github.com/ros2/launch_ros/blob/58334b4447daf1d86aa7e17bb5e1b9ebb74301b4/launch_ros/launch_ros/actions/node.py#L319) is where it is being parsed.

@ivanpauno Mentioning you as it's similar to the other issue you dealt with.

**Comment by ivanpauno** [comment]
@rob-clarke you're correct, the correct attribute is `namespace` and not `ns`.
A PR is welcomed.

> defines a ns attribute but this appears to have been renamed to namespace

The attribut has always been `namespace`, but it was wrongly documented as `ns` in the schema.

**Comment by christophebedard** [comment]
I can take care of this (if @rob-clarke isn't already on it) and also add `ros_args` (https://github.com/ros2/launch_ros/pull/253) at the same time

**Comment by christophebedard** [comment]
> I can take care of this (if @rob-clarke isn't already on it) and also add `ros_args` ([ros2/launch_ros#253](https://github.com/ros2/launch_ros/pull/253)) at the same time

I just went ahead and did it: #318
