### ISSUE TITLE
can we add a "date written" to the design docs?

### ISSUE THREAD

**Issue by flynneva** [ros2/design#320]
on a few of the design docs some information is already old. could we put a date at the top of the article to show when it was written to help understand how recent the information is?

**Comment by clalancette** [comment]
It seems reasonable to me, though we'd have to go back and do some archaeology to add dates to the articles that already exist.

**Comment by flynneva** [comment]
@clalancette honestly even just a year would help. I think a lot of the design docs were written in like 2016 or 2017 or something.

Just getting the rough idea of how old they are would give people context I think.
