### ISSUE TITLE
how you configured opentcs nena ros2 adapter to your agv?

### ISSUE THREAD

**Issue by jaanu-11** [ros2/design#334]
actually i followed documentation of opentcs-nena , i found that you succeded in connecting that , im greatfull if you can help me with this , here  im figuring out  how actually ros2 adapter connects with my agv , should i write custom code for it or is there any way to connect directly?

**Comment by clalancette** [comment]
Please open questions like this on https://answers.ros.org, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
