### ISSUE TITLE
where is the discauss of register callback and run callback?

### ISSUE THREAD

**Issue by fengmao31** [ros2/design#336]
I remember I have read the article about ros client’s register callback and action callback design in ros document. It discusses different ways to register the callback and run callback. Also, it can use poller to get callbacks to run or use trigger to run callbacks. I want to find it.

**Comment by fujitatomoya** [comment]
can you take a look at https://discourse.ros.org/t/where-is-the-discauss-of-register-callback-and-run-callback/34136.

i think it is not recommended to post the same questions on multiple site...

**Comment by fengmao31** [comment]
I donnot mean to find tutorial to know how to use ros client. That article I want to find is about how to and why ros use that callback desgin. I use ros for many years. I forget where is the article.

**Comment by fengmao31** [comment]
I already ask questions to https://robotics.stackexchange.com/. Thank you for your answer.
