### ISSUE TITLE
Should these specs (for me, articles/080_ros_documentation_system.md) be kept up to date?

### ISSUE THREAD

**Issue by rkent** [ros2/design#342]
I've mostly followed [080_ros_documentation_system.md](https://raw.githubusercontent.com/ros2/design/refs/heads/gh-pages/articles/080_ros_documentation_system.md) in my work on rosindex and rosdoc2, but occasionally there are differences. And at some point I might want to make some more major proposals.

Are these design documents supposed to be kept up to date, and are a good place to discuss changes, or has that ship largely sailed? Do people still follow this repo?

**Comment by clalancette** [comment]
> Are these design documents supposed to be kept up to date, and are a good place to discuss changes, or has that ship largely sailed? Do people still follow this repo?

For now, yes, the design documents should be kept up-to-date.  The long-term goal is to deprecate this site and move the content elsewhere (or remove it), but we don't currently have anyone assigned to that task.
